### ISSUE TITLE
AttributeError: module 'utils' has no attribute 'OOV'

### ISSUE THREAD

**Issue by RonenHong** [taishi-i/nagisa#14] opened 2019-05-22 07:14 UTC
Hi, 
I got error in 'import nagisa' as below

OOV = utils.OOV
AttributeError: module 'utils' has no attribute 'OOV'

I did 'pip install nagisa' on the conda envrionment python 3.7 and 3.6
I ran it on my Mac.

**Comment by taishi-i** [comment] 2019-05-22 07:33
Hi @RonenHong,
Thank you for using nagisa.

Does _utils.py_ exist in the working directory?
Since it exists in _utils.py_ in the working directory, I think that it is imported first and an error occurs.
Could you rename _utils.py_ into _data_utils.py?_  I think that errors can be avoided by renaming.

**Comment by RonenHong** [comment] 2019-05-24 05:53
My bad, that's the problem. I have my utils.py.
Thank you so much

**Comment by ssaikiran123** [comment] 2020-06-16 14:20
Hello Team I am facing same problem as mentioned by @RonenHong and the issue because in prepro.py file we are using OOV = utils.OOV
PAD = utils.PAD

**Comment by taishi-i** [comment] 2020-06-16 14:36
Hi @ssaikiran123,
Thank you for using nagisa.

The first thing I want to check is: Does utils.py exist in your working directory?
Since it exists in the working directory, could you rename utils.py into data_utils.py?
I guess that errors can be avoided by renaming.

**Comment by ssaikiran123** [comment] 2020-06-16 15:40
Yes i tried it by renaming but still facing same issue @taishi-i

**Comment by ssaikiran123** [comment] 2020-06-16 15:54
When i am trying to run the individual python file i.e __init__.py,model.prepro,tagger,train,utils for all same AttributeError: module 'utils' has no attribute 'OOV'
Error:
(![image](https://user-images.githubusercontent.com/59430646/84796644-7b24cd80-b016-11ea-8788-1a511f1c82b3.png)

**Comment by taishi-i** [comment] 2020-06-16 16:20
Thank you for sharing your screenshot.
You don't need to rename utils.py in nagisa-master/nagisa.  Please download the repository again.

Assuming that you run  `python main.py`, this AttributeError occurs when the working directory structure is as follows.

```
working/
├── utils.py
└── main.py

0 directories, 2 files
```

If utils.py exists in your working directory, could you rename utils.py into data_utils.py as follows?

```
working/
├── data_utils.py
└── main.py

0 directories, 2 files
```

If this does not resolve the error, could you share the error with the python file you ran?

**Comment by ssaikiran123** [comment] 2020-06-16 20:37
Hello @taishi-i thanks for your response , I didn't get this part Assuming that you run python main.py.
As suggested i downloaded the repository again.I have checked there is no utils.py in my working directory .
Please suggest me how do i check whether the utils.py exists in your working directory just for clarification.

Error :

**Comment by taishi-i** [comment] 2020-06-17 02:53
Hi @ssaikiran123,

As far as the errors are concerned, the following two things seem to be the cause of the errors.
1) Running a python script (nagisa.py) in nagisa-master
2) Using the same file name (nagisa.py) as the library (nagisa)

Could you make a new directory (e.g, working) and rename your python script (nagisa.py -> main.py) as follows?

Before
```
nagisa-master/
└── nagisa.py
0 directories, 1 file
```

After
```
working/
└── main.py
0 directories, 1 file
```

**Comment by ssaikiran123** [comment] 2020-06-17 08:27
Hello @taishi-i as suggested i changed the folder names and nagisa_test.py to work_test.py but still facing the issue.
(base) D:\working code\working\test>python
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. o
Type "help", "copyright", "credits" or "license" for more information.
>>> import nagisa
[dynet] random seed: 1234
[dynet] allocating memory: 32MB
[dynet] memory allocation done.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\nagisa\__init__.py", line 3, in <module>
    from nagisa.train import fit
  File "C:\ProgramData\Anaconda3\lib\site-packages\nagisa\train.py", line 12, in <module>
    import prepro
  File "C:\ProgramData\Anaconda3\lib\site-packages\nagisa\prepro.py", line 11, in <module>
    OOV = utils.OOV
AttributeError: module 'utils' has no attribute 'OOV'

This is the directory now 
D:\working code\working\test

**Comment by taishi-i** [comment] 2020-06-17 10:01
I don't think there is any problem with your directory structure and the file name.
Thank you for trying out my suggestions.

I want to have a check that nagisa is installed correctly.
Could you try to uninstall it and reinstall it again? 

Uninstall: `pip uninstall nagisa`
Install: `pip install nagisa`

After `pip install nagisa`, did you get the following message?
```
Installing collected packages: nagisa
Successfully installed nagisa-0.2.6
```

**Comment by ssaikiran123** [comment] 2020-06-17 15:01
Hello @taishi-i i have trouble in pip installing nagisa so i am using this repository as other option
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by taishi-i** [comment] 2020-06-17 15:34
Hi @ssaikiran123,
Cython does not seem to be installed.
Before installing nagisa, could you install _cython_ library?
```
pip install --upgrade cython
pip install nagisa
```

**Comment by ssaikiran123** [comment] 2020-06-17 16:22
Hello Taishi-I/Nagisa

I Have installed cython but still facing issue in pip installing nagisa. I
request you to please help me on this.

Thanks & Regards
Saikiran
8971647885

**Comment by taishi-i** [comment] 2020-06-17 18:35
Hi @ssaikiran123,
I think it's probably due to not installing the library correctly.
As it is not related to this issue (#14 AttributeError), could you create a new issue?
So let's discuss the Installation problems there. I will close this issue.

**Closed by taishi-i** 2020-06-17 18:35 UTC
